name: workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flask
  - keyboard
  - pandas
  - win32gui
  - psutil
  - paperclip
  - pygetwindow
  - networkx
  - plotly
  - matplotlib
  - seaborn
